[build.environment]
  HUGO_VERSION = "0.162.0"

[build]
  base = "site"
  command = "hugo --gc --minify"
  publish = "public"

[context.deploy-preview]
  command = "hugo --gc --minify --buildDrafts --buildFuture"

[dev]
  framework = "hugo"
  targetPort = 3000
