baseURL = "/"
theme = "hugo-bearblog"

title = "Wheeling Ice"
author = "Wheeling Ice"
copyright = "Copyright © 2026, Wheeling Ice."
locale = "en-US"

enableRobotsTXT = true
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
ignoreFiles = ["content/contact/.*", "content/products/.*", "content/values/.*"]

[permalinks]
blog = "/:slug/"

[params]
description = "Music for the People"
favicon = "favicon.ico?v=2"
images = ["img/wheelingice-logo.png"]
title = "Wheeling Ice"
dateFormat = "January 2, 2006"
hideMadeWithLine = true
