baseURL = "/"
theme = "hugo-bearblog"

title = "Wheeling Ice"
author = "Wheeling Ice"
copyright = "Copyright © 2026, Wheeling Ice."
languageCode = "en-US"

enableRobotsTXT = true
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[permalinks]
blog = "/:slug/"

[params]
description = "Music for the People"
favicon = "img/favicon-32x32.png"
images = ["img/og-image.jpg"]
title = "Wheeling Ice"
dateFormat = "January 2, 2006"
